element:
  version: '1.2.2'
  css:
    component:
      css/multiselect-dropdown.css: {}
  js:
    js/dist/multiselect-dropdowns.js: { attributes: { type: module } }
    js/dist/multiselect-dropdown.js: { attributes: { type: module } }
  dependencies:
    - core/drupal
    - core/once

field_widget:
  version: '1.2.2'
  css:
    component:
      css/multiselect-dropdown-field-widget.css: {}
  dependencies:
    - multiselect_dropdown/element

views:
  version: '1.2.2'
  js:
    js/dist/multiselect-dropdown-views.js: { attributes: { type: module } }
  dependencies:
    - multiselect_dropdown/element
